# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: tooltime-consumer
frameworkVersion: '2'
variablesResolutionMode: 20210219
plugins:
  - serverless-s3-sync
custom:
  s3DeployTime: ${file(./sls_s3_deploy_date.js)}
  s3Sync:
    - bucketName: tooltime-consumer # required
      #bucketPrefix: ${self:custom.s3DeployTime}/ # optional
      localDir: dist # required
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    VUE_APP_API_URL: http://localhost:8000
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: tooltime-consumer
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
                  - /*
        Bucket: !Ref S3Bucket
  Outputs:
    WebsiteURL:
      Value: !GetAtt
        - S3Bucket
        - WebsiteURL
      Description: URL for website hosted on S3
    S3BucketSecureURL:
      Value: !Join
        - ''
        - - 'https://'
          - !GetAtt
            - S3Bucket
            - DomainName
      Description: Name of S3 bucket to hold website content
